micronaut:
  application:
    name: baldr

  server:
    port: 8080

db:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://baldr-pod-db:5432/baldr
  username: "baldr"
  password: "baldr"

flyway:
  migrations:
    - /migrations
  schemas:
    - public

security:
  url: security
