apiVersion: v1
kind: Namespace
metadata:
  name: rafflethor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rafflethor
  namespace: rafflethor
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rafflethor
    spec:
      containers:
      - image: rafflethor-docker-rafflethor.bintray.io/baldr:0.1-alpine
        imagePullPolicy: Always
        name: rafflethor-api
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: rafflethor
  namespace: rafflethor
spec:
  ports:
  - port: 80
    targetPort: 5050
    protocol: TCP
  selector:
    app: rafflethor
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rafflethor
  namespace: rafflethor
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: baldr.services.rafflethor.io
    http:
      paths:
      - path: /
        backend:
          serviceName: rafflethor
          servicePort: 80
